/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicLibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {

    @Test //1
    public void testRoll() {
        int n = 6;
        int[] rolls = Library.roll(n);
        int expected = n;
        int actual = rolls.length;
        assertEquals(expected, actual);
    }
    @Test //2
    public void testRoll2() {
        int n = 12;
        int[] rolls = Library.roll(n);
        int expected = n;
        int actual = rolls.length;
        assertEquals(expected, actual);
    }

    @Test //3
    public void testDuplicates() {
        int[] array1 = {1, 2, 3, 1};
        boolean result = Library.containsDuplicates(array1);
        assertTrue(
                "library should return true or false",
                result
        );
    }
    @Test //4
    public void testDuplicates2() {
        int[] array1 = {1, 2, 3};
        boolean result = Library.containsDuplicates(array1);
        assertFalse(
                "library should return true or false",
                result
        );
    }

    @Test //5
    public void testCalculateAverage(){
        double[] arr = {5, 10, 15, 20, 25};
        String expected = "15.00";
        String actual = String.format("%.2f",Library.calculateAverage(arr));
        assertEquals(expected, actual);
    }
    @Test //6
    public void testCalculateAverage2(){
        double[] arr = {2.7, 18.3, 12.6, 9.1, 31.0, 6.6};
        String expected = "13.38";
        String actual = String.format("%.2f",Library.calculateAverage(arr));
        assertEquals(expected, actual);
    }

    @Test //7
    public void testLowAverage(){

        int[][] arr = { //ARRAY OF ARRAYS FROM LAB DOC
                {66, 64, 58, 65, 71, 57, 60}, // 63.00
                {57, 65, 65, 70, 72, 65, 51}, // 63.57
                {55, 54, 60, 53, 59, 57, 61}, // 57.00
                {65, 56, 55, 52, 55, 62, 57}  // 57.42
        };
        int[] expected = {55, 54, 60, 53, 59, 57, 61};
        int[] actual = Library.calculateLowAverage(arr);
        assertArrayEquals(expected, actual);
    }
    @Test //8
    public void testLowAverage2(){

        int[][] arr = { //ARRAY OF ARRAYS FROM LAB DOC
                {352, 856, 133, 37, 70, 8, 432, 35}, // 240.37
                {123, 76, 97, 123, 46, 45, 253, 2}, // 95.50
                {86, 24, 968, 5313, 64, 64, 13}, // 933.1429
                {47, 4758, 534, 1, 5, 654, 1},  // 857.14
                {123, 475, 235, 785, 1235, 1, 1, 457, 329} // 404.55
        };
        int[] expected = {123, 76, 97, 123, 46, 45, 253, 2};
        int[] actual = Library.calculateLowAverage(arr);
        assertArrayEquals(expected, actual);
    }

    @Test
    public void testWeatherData(){
        int[][] arr = {
                {66, 64, 58, 65, 71, 57, 60},
                {57, 65, 65, 70, 72, 65, 51},
                {55, 54, 60, 53, 59, 57, 61},
                {65, 56, 55, 52, 55, 62, 57}
        };

        String expected = "High: 72";
        String actual = Library.weatherData(arr);
        assertEquals(expected, actual);
    }
}
