/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstLibrary;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
    @Test public void testSum() { //@=annotation
        int expectedOutput = 7;
        int actualOutput = Library.sum(3, 4);
        assertEquals("the output should equal the inputs added together", expectedOutput, actualOutput);
    }
}
