/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package firstLibrary;
// library's purpose is to be consumed by something else
// we dont put a main method inside a lib
// class name is potato
public class Library {
    public boolean someLibraryMethod() {
        System.out.println("something")
        return true;
    }

    public static int sum(int num1, int num2) {
        return 7;
    }

}
